language: java
addons:
  sonarcloud:
    organization: "zero-bs"
    token:
      secure: "fQp1IbQA2wCvbTM5qqUx7TlIeaDStXJ+qSRN92+REV+ZbjYtA3iZsMSqd8RXzWBTbo7ijfhoos1dYqlKC3kRs8/EDVlewDxFJAV15PK67Lz6Se2IWOZAcJm66wm4HFh8W+DrPra+2Y4nISRPX6onqRpK26ZbvpJAuJWys28UWq6BpV6r7zZXGzSharEDwA/sviFWqltddd/bgeYCOdgwAPa1aXxT6/Jj9qaV7Zhweillv0qL4kXJV6f5lXZKaZzny1brIcLjL8wBA/qUcK2ChoBop4U+Cgiig/ZC80MvftjUrNXWFOHlJ+QPZ8MpMk08pE2GGuMinA1L2AzMTKiorDFn9iN20P2+nPw5vRDg5wIox4RB3hyajwcTyTca/E5DSZJRziOoRARLTujVsPyEoAIGybhWLo6OCG0ap+xB1w0CZ39E3jxNfqUb2H7L79rYiSkpXRbUYTS1ggRkDqlb5WZMDbBLeW4q3gyS7oFzpRNfihOgokr/1rn9nlruLTok9BjOzWWDNAUFV4EeiHEg+4dfkFTJLPXFzo382I4ZOxfP4FK9kzUgEOo7ao50G9CLcs+SuT6jejOkjYo4kZpCg6YBIMSD3JvzVdqbQOfykzDpOjrsIRZHPxL8SyE1/Z9ZgvH7MoX3UIhzORJ/J0aEugDlsqJUedNdXWIznWR099c="

script:
  - ./gradlew sonarqube
before_install:
  - chmod +x gradlew