server:
  port: 2194
  servlet:
    context-path: /api
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
locale:
  default: en-US
  supported: ${locale.default}, fr-FR #add comma separated values like: ${locale.default}, fr-FR